export const STYLES = [
  '.dmi-page{max-width:820px;padding:8px 4px 32px;color:var(--dsw-alias-label-primary,CanvasText)}',
  '.dmi-head{padding:8px 0 22px;border-bottom:1px solid var(--dsw-alias-border-line,rgba(0,0,0,.14))}',
  '.dmi-eyebrow{margin:0 0 8px;font-size:11px;font-weight:700;letter-spacing:.12em;color:var(--dsw-alias-state-success-primary,#167c4c)}',
  '.dmi-title{margin:0;font-size:28px;line-height:1.15;letter-spacing:-.02em}',
  '.dmi-intro{max-width:620px;margin:9px 0 0;color:var(--dsw-alias-label-secondary,inherit);line-height:1.55}',
  '.dmi-block{padding:22px 0;border-bottom:1px solid var(--dsw-alias-border-line,rgba(0,0,0,.12))}',
  '.dmi-label,.dmi-legend{display:block;margin:0 0 9px;font-size:13px;font-weight:650}',
  '.dmi-input{box-sizing:border-box;width:100%;height:40px;padding:0 12px;border:1px solid var(--dsw-alias-border-line,rgba(0,0,0,.22));border-radius:7px;background:var(--dsw-alias-bg-layer-1,Canvas);color:inherit;font:inherit}',
  '.dmi-input:focus{outline:2px solid var(--dsw-alias-state-success-primary,#167c4c);outline-offset:1px}',
  '.dmi-hint{margin:7px 0 0;font-size:12px;color:var(--dsw-alias-label-secondary,inherit)}',
  '.dmi-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}',
  '.dmi-choice{display:flex;align-items:center;gap:9px;min-height:40px;padding:0 11px;border:1px solid var(--dsw-alias-border-line,rgba(0,0,0,.16));border-radius:7px;cursor:pointer}',
  '.dmi-choice:has(input:checked){border-color:var(--dsw-alias-state-success-primary,#167c4c);background:color-mix(in srgb,var(--dsw-alias-state-success-primary,#167c4c) 7%,transparent)}',
  '.dmi-choice input{accent-color:var(--dsw-alias-state-success-primary,#167c4c)}',
  '.dmi-details{padding:14px 0;border-bottom:1px solid var(--dsw-alias-border-line,rgba(0,0,0,.12))}',
  '.dmi-details summary{cursor:pointer;font-size:13px;font-weight:650}',
  '.dmi-origins{display:flex;gap:8px;margin-top:12px;flex-wrap:wrap}',
  '.dmi-origin{display:flex;align-items:center;gap:7px;padding:7px 10px;border:1px solid var(--dsw-alias-border-line,rgba(0,0,0,.16));border-radius:999px;cursor:pointer}',
  '.dmi-actions{display:flex;align-items:center;gap:10px;padding:20px 0 8px;flex-wrap:wrap}',
  '.dmi-button{min-height:40px;padding:0 15px;border-radius:7px;border:1px solid var(--dsw-alias-border-line,rgba(0,0,0,.2));background:transparent;color:inherit;font:inherit;font-weight:650;cursor:pointer}',
  '.dmi-button:hover:not(:disabled){border-color:var(--dsw-alias-state-success-primary,#167c4c)}',
  '.dmi-primary{border-color:var(--dsw-alias-state-success-primary,#167c4c);background:var(--dsw-alias-state-success-primary,#167c4c);color:var(--dsw-alias-label-primary-foreground,#fff)}',
  '.dmi-button:disabled{opacity:.5;cursor:not-allowed}',
  '.dmi-result{margin-top:18px;padding-top:18px;border-top:2px solid var(--dsw-alias-label-primary,CanvasText)}',
  '.dmi-resultHead{display:flex;align-items:baseline;justify-content:space-between;gap:12px}',
  '.dmi-resultHead h3{margin:0;font-size:18px}',
  '.dmi-project{margin:4px 0 14px;overflow-wrap:anywhere;font:12px ui-monospace,monospace;color:var(--dsw-alias-label-secondary,inherit)}',
  '.dmi-list{list-style:none;margin:0;padding:0}',
  '.dmi-row{display:grid;grid-template-columns:64px minmax(0,1fr);gap:10px;padding:10px 0;border-top:1px solid var(--dsw-alias-border-line,rgba(0,0,0,.1))}',
  '.dmi-status{font-size:11px;font-weight:700;text-transform:uppercase;color:var(--dsw-alias-label-secondary,inherit)}',
  '.dmi-row[data-status="done"] .dmi-status,.dmi-row[data-status="move"] .dmi-status{color:var(--dsw-alias-state-success-primary,#167c4c)}',
  '.dmi-row[data-status="error"] .dmi-status{color:var(--dsw-alias-state-warn-primary,#b3312d)}',
  '.dmi-rowTitle{font-size:13px;font-weight:600;overflow-wrap:anywhere}',
  '.dmi-rowNote{margin-top:3px;font-size:12px;line-height:1.45;color:var(--dsw-alias-label-secondary,inherit);overflow-wrap:anywhere}',
  '.dmi-warning{margin:12px 0 0;padding:11px 12px;border-left:3px solid var(--dsw-alias-state-warn-primary,#b36b00);background:color-mix(in srgb,var(--dsw-alias-state-warn-primary,#b36b00) 8%,transparent);font-size:12px;line-height:1.5}',
  '.dmi-report{margin-top:12px}',
  '.dmi-report summary{cursor:pointer;font-size:12px;font-weight:650}',
  '.dmi-report pre{max-height:340px;overflow:auto;margin:9px 0 0;padding:12px;border-radius:7px;background:var(--dsw-alias-bg-layer-1,#111);font:11px/1.5 ui-monospace,monospace;white-space:pre-wrap}',
  '.dmi-star{display:inline-block;margin-top:15px;color:var(--dsw-alias-state-success-primary,#167c4c);font-size:13px;font-weight:700}',
  '.dmi-error{margin-top:16px;padding:12px;border-left:3px solid var(--dsw-alias-state-warn-primary,#b3312d);background:color-mix(in srgb,var(--dsw-alias-state-warn-primary,#b3312d) 8%,transparent)}',
  '@media(max-width:640px){.dmi-grid{grid-template-columns:1fr}.dmi-title{font-size:24px}.dmi-row{grid-template-columns:52px minmax(0,1fr)}}',
  '@media(prefers-reduced-motion:no-preference){.dmi-button{transition:background-color .15s ease,border-color .15s ease}}',
].join('');
